// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw1v214098Xlf9MkTkDUjdhEfdzq7ulco',
    appId: '1:769082015702:web:416f034f9d06504beaae77',
    messagingSenderId: '769082015702',
    projectId: 'nutrigenius-logreg',
    authDomain: 'nutrigenius-logreg.firebaseapp.com',
    storageBucket: 'nutrigenius-logreg.firebasestorage.app',
    measurementId: 'G-7CBGY0MDEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcsw68YxQrcjlV6934yzEI4s4OwiTV9KI',
    appId: '1:769082015702:android:90de8bf216e6c274eaae77',
    messagingSenderId: '769082015702',
    projectId: 'nutrigenius-logreg',
    storageBucket: 'nutrigenius-logreg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8GhO54zqzI9-QwPLyRxNt3cQyC99yOk',
    appId: '1:769082015702:ios:e975b471a5a72747eaae77',
    messagingSenderId: '769082015702',
    projectId: 'nutrigenius-logreg',
    storageBucket: 'nutrigenius-logreg.firebasestorage.app',
    iosBundleId: 'com.example.nutrigenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8GhO54zqzI9-QwPLyRxNt3cQyC99yOk',
    appId: '1:769082015702:ios:e975b471a5a72747eaae77',
    messagingSenderId: '769082015702',
    projectId: 'nutrigenius-logreg',
    storageBucket: 'nutrigenius-logreg.firebasestorage.app',
    iosBundleId: 'com.example.nutrigenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw1v214098Xlf9MkTkDUjdhEfdzq7ulco',
    appId: '1:769082015702:web:eba8245300aeef09eaae77',
    messagingSenderId: '769082015702',
    projectId: 'nutrigenius-logreg',
    authDomain: 'nutrigenius-logreg.firebaseapp.com',
    storageBucket: 'nutrigenius-logreg.firebasestorage.app',
    measurementId: 'G-20DVHTDRJM',
  );
}
