// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzvxkndWPjXrH3G4g7SJomFHSLoP-B_0',
    appId: '1:176691529828:web:1dcd4fb581544089f7b771',
    messagingSenderId: '176691529828',
    projectId: 'nutrigenius-324a0',
    authDomain: 'nutrigenius-324a0.firebaseapp.com',
    storageBucket: 'nutrigenius-324a0.firebasestorage.app',
    measurementId: 'G-TVN6DWKTZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOg0HFBJs_94ihFAbAjEawllPDNtjc_FA',
    appId: '1:176691529828:android:e8c2994842babb4ff7b771',
    messagingSenderId: '176691529828',
    projectId: 'nutrigenius-324a0',
    storageBucket: 'nutrigenius-324a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbfyrwCX8-kHsGh9duS_ttKuWCuKXBAU',
    appId: '1:176691529828:ios:bb7138adb3031d47f7b771',
    messagingSenderId: '176691529828',
    projectId: 'nutrigenius-324a0',
    storageBucket: 'nutrigenius-324a0.firebasestorage.app',
    iosClientId: '176691529828-060ot1ekh5sd9tnd1kpkumhlvg2uam69.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrigenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPbfyrwCX8-kHsGh9duS_ttKuWCuKXBAU',
    appId: '1:176691529828:ios:bb7138adb3031d47f7b771',
    messagingSenderId: '176691529828',
    projectId: 'nutrigenius-324a0',
    storageBucket: 'nutrigenius-324a0.firebasestorage.app',
    iosClientId: '176691529828-060ot1ekh5sd9tnd1kpkumhlvg2uam69.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrigenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzvxkndWPjXrH3G4g7SJomFHSLoP-B_0',
    appId: '1:176691529828:web:a25d482edbb3d50ff7b771',
    messagingSenderId: '176691529828',
    projectId: 'nutrigenius-324a0',
    authDomain: 'nutrigenius-324a0.firebaseapp.com',
    storageBucket: 'nutrigenius-324a0.firebasestorage.app',
    measurementId: 'G-62ZB0JDP2N',
  );
}
